function grilla () {
    $("#list27").jqGrid({
		url:'includes/grillaUsuarios.php',
		datatype: "json",
		height: 240,
		width:1024,
		colNames:['Id','Documento', 'Ciu_exp','pri_nom','seg_nom','pri_ape','seg_ape',
		'genero','fec_gra','titulo','programa','facultad','fec_nac','direccion',
		'telefono','celular','correo','est_civil'],
		colModel:[
			{name:'Id',index:'id', width:40, formatter: "integer"},
			{name:'documento',index:'num_doc', width:100},
			{name:'Ciu_exp',index:'nom_ciu', width:150},
			{name:'pri_nom',index:'pri_nom', width:100},
			{name:'seg_nom',index:'seg_nom', width:100},
			{name:'pri_ape',index:'pri_ape', width:100},
			{name:'seg_ape',index:'seg_ape', width:150},
			{name:'genero',index:'genero', width:100, stype:'select',editoptions:{value:":All;M:M;F:F"}},
			{name:'fec_gra',index:'fecha_egre', width:100,sorttype:'string',searchoptions:{sopt:['eq','bw','bn','cn','nc','ew','en']}},
			{name:'titulo',index:'nombre', width:100},
			{name:'programa',index:'nombre', width:100},
			{name:'facultad',index:'nombre', width:100},
			{name:'fec_nac',index:'fechanacimiento', width:100},
			{name:'direccion',index:'direccion', width:100},
			{name:'telefono',index:'telefono', width:100},
			{name:'celular',index:'celular', width:100},
			{name:'correo',index:'correo', width:100},
			{name:'est_civil',index:'descripcion', width:100},

		],
		JsonReader: {repeatitems: false},
		width:1050,
		rowNum:10,
		rowTotal: 2000,
		rowList : [10,20,30,50],
		loadonce:true,
		mtype: "POST",
		rownumbers: true,
		rownumWidth: 40,
		gridview: true,
		pager: '#pager27',
		sortname: 'id',
		viewrecords: true,
		sortorder: "asc",
		editurl: "includes/grillaUsuarios.php",
		cellEdit:true,			
	});
	jQuery("#list27").jqGrid('navGrid',"#pager27",{edit:false,add:false,search:false,del:true,refresh:false}); 
	$("#list27").jqGrid("filterToolbar",{searchOperators : true});
}